linters:
  enable-all: true
  disable:
    - canonicalheader
    - contextcheck
    - cyclop
    - depguard
    - err113           # NOTE: look into re-enabling this (do not define dynamic errors, use wrapped static errors instead)
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - goimports
    - gomnd
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mirror
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - protogetter      # NOTE: look into re-enabling this (avoid direct access to proto field)
    - tagliatelle
    - varnamelen
    - wrapcheck        # NOTE: look into re-enabling this (error returned from external package is unwrapped)
    - wsl
linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*net/http.ResponseWriter).Write
      - (net/http.Server).Serve
      - (*net/http.Server).Serve
      - (google.golang.org/grpc.Server).Serve
      - (*google.golang.org/grpc.Server).Serve
issues:
  uniq-by-line: false
run:
  issues-exit-code: 1
  timeout: 13m
